// ignore_for_file: file_names

import 'package:deen/Models/videomodel.dart';
import 'package:deen/core/utils/appstring/app_string.dart';
import 'package:deen/core/utils/appvideos/appvideos.dart';

class MixvideoData {
  static List<Video> mixvideo = [
    Video(Appvideos.mixstories[0], title: Appstring.mixStoriesTitles[0]),
    Video(Appvideos.mixstories[1], title: Appstring.mixStoriesTitles[1]),
    Video(Appvideos.mixstories[2], title: Appstring.mixStoriesTitles[2]),
    Video(Appvideos.mixstories[3], title: Appstring.mixStoriesTitles[3]),
    Video(Appvideos.mixstories[4], title: Appstring.mixStoriesTitles[4]),
    Video(Appvideos.mixstories[5], title: Appstring.mixStoriesTitles[5]),
    Video(Appvideos.mixstories[6], title: Appstring.mixStoriesTitles[6]),
    Video(Appvideos.mixstories[7], title: Appstring.mixStoriesTitles[7]),
    Video(Appvideos.mixstories[8], title: Appstring.mixStoriesTitles[8]),
    Video(Appvideos.mixstories[9], title: Appstring.mixStoriesTitles[9]),
    Video(Appvideos.mixstories[10], title: Appstring.mixStoriesTitles[10]),
    Video(Appvideos.mixstories[11], title: Appstring.mixStoriesTitles[11]),
    Video(Appvideos.mixstories[12], title: Appstring.mixStoriesTitles[12]),
    Video(Appvideos.mixstories[13], title: Appstring.mixStoriesTitles[13]),
    Video(Appvideos.mixstories[14], title: Appstring.mixStoriesTitles[14]),
    Video(Appvideos.mixstories[15], title: Appstring.mixStoriesTitles[15]),
    Video(Appvideos.mixstories[16], title: Appstring.mixStoriesTitles[16]),
    Video(Appvideos.mixstories[17], title: Appstring.mixStoriesTitles[17]),
    Video(Appvideos.mixstories[18], title: Appstring.mixStoriesTitles[18]),
    Video(Appvideos.mixstories[19], title: Appstring.mixStoriesTitles[19]),
    Video(Appvideos.mixstories[20], title: Appstring.mixStoriesTitles[20]),
    Video(Appvideos.mixstories[21], title: Appstring.mixStoriesTitles[21]),
    Video(Appvideos.mixstories[22], title: Appstring.mixStoriesTitles[22]),
    Video(Appvideos.mixstories[23], title: Appstring.mixStoriesTitles[23]),
    Video(Appvideos.mixstories[24], title: Appstring.mixStoriesTitles[24]),
    Video(Appvideos.mixstories[25], title: Appstring.mixStoriesTitles[25]),
    Video(Appvideos.mixstories[26], title: Appstring.mixStoriesTitles[26]),
    Video(Appvideos.mixstories[27], title: Appstring.mixStoriesTitles[27]),
    Video(Appvideos.mixstories[28], title: Appstring.mixStoriesTitles[28]),
    Video(Appvideos.mixstories[29], title: Appstring.mixStoriesTitles[29]),
    Video(Appvideos.mixstories[30], title: Appstring.mixStoriesTitles[30]),
    Video(Appvideos.mixstories[31], title: Appstring.mixStoriesTitles[31]),
    Video(Appvideos.mixstories[32], title: Appstring.mixStoriesTitles[32]),
  ];
}

class ProphetMohamedvideoData {
  static List<Video> prophetMohamedvideo = [
    Video(Appvideos.prophetmohamedstories[0],
        title: Appstring.prophetMohamedTitles[0]),
    Video(Appvideos.prophetmohamedstories[1],
        title: Appstring.prophetMohamedTitles[1]),
    Video(Appvideos.prophetmohamedstories[2],
        title: Appstring.prophetMohamedTitles[2]),
    Video(Appvideos.prophetmohamedstories[3],
        title: Appstring.prophetMohamedTitles[3]),
    Video(Appvideos.prophetmohamedstories[4],
        title: Appstring.prophetMohamedTitles[4]),
    Video(Appvideos.prophetmohamedstories[5],
        title: Appstring.prophetMohamedTitles[5]),
    Video(Appvideos.prophetmohamedstories[6],
        title: Appstring.prophetMohamedTitles[6]),
    Video(Appvideos.prophetmohamedstories[7],
        title: Appstring.prophetMohamedTitles[7]),
    Video(Appvideos.prophetmohamedstories[8],
        title: Appstring.prophetMohamedTitles[8]),
    Video(Appvideos.prophetmohamedstories[9],
        title: Appstring.prophetMohamedTitles[9]),
    Video(Appvideos.prophetmohamedstories[10],
        title: Appstring.prophetMohamedTitles[10]),
  ];
}

class GhzwatvideoData {
  static List<Video> ghzwatvideo = [
    Video(Appvideos.ghzwatstories[0], title: Appstring.ghazwaTitles[0]),
    Video(Appvideos.ghzwatstories[1], title: Appstring.ghazwaTitles[1]),
    Video(Appvideos.ghzwatstories[2], title: Appstring.ghazwaTitles[2]),
    Video(Appvideos.ghzwatstories[3], title: Appstring.ghazwaTitles[3]),
    Video(Appvideos.ghzwatstories[4], title: Appstring.ghazwaTitles[4]),
    Video(Appvideos.ghzwatstories[5], title: Appstring.ghazwaTitles[5]),
    Video(Appvideos.ghzwatstories[6], title: Appstring.ghazwaTitles[6]),
    Video(Appvideos.ghzwatstories[7], title: Appstring.ghazwaTitles[7]),
    Video(Appvideos.ghzwatstories[8], title: Appstring.ghazwaTitles[8]),
    Video(Appvideos.ghzwatstories[9], title: Appstring.ghazwaTitles[9]),
    Video(Appvideos.ghzwatstories[10], title: Appstring.ghazwaTitles[10]),
    Video(Appvideos.ghzwatstories[11], title: Appstring.ghazwaTitles[11]),
    Video(Appvideos.ghzwatstories[12], title: Appstring.ghazwaTitles[12]),
    Video(Appvideos.ghzwatstories[13], title: Appstring.ghazwaTitles[13]),
    Video(Appvideos.ghzwatstories[14], title: Appstring.ghazwaTitles[14]),
    Video(Appvideos.ghzwatstories[15], title: Appstring.ghazwaTitles[15]),
    Video(Appvideos.ghzwatstories[16], title: Appstring.ghazwaTitles[16]),
    Video(Appvideos.ghzwatstories[17], title: Appstring.ghazwaTitles[17]),
    Video(Appvideos.ghzwatstories[18], title: Appstring.ghazwaTitles[18]),
    Video(Appvideos.ghzwatstories[19], title: Appstring.ghazwaTitles[19]),
    Video(Appvideos.ghzwatstories[20], title: Appstring.ghazwaTitles[20]),
    Video(Appvideos.ghzwatstories[21], title: Appstring.ghazwaTitles[21]),
    Video(Appvideos.ghzwatstories[22], title: Appstring.ghazwaTitles[22]),
    Video(Appvideos.ghzwatstories[23], title: Appstring.ghazwaTitles[23]),
    Video(Appvideos.ghzwatstories[24], title: Appstring.ghazwaTitles[24]),
    Video(Appvideos.ghzwatstories[25], title: Appstring.ghazwaTitles[25]),
    Video(Appvideos.ghzwatstories[26], title: Appstring.ghazwaTitles[26]),
    Video(Appvideos.ghzwatstories[27], title: Appstring.ghazwaTitles[27]),
    Video(Appvideos.ghzwatstories[28], title: Appstring.ghazwaTitles[28]),
  ];
}

class ProphetsvideoData {
  static List<Video> prophetsvideo = [
    Video(Appvideos.prophetsstories[0], title: Appstring.prophetsTitles[0]),
    Video(Appvideos.prophetsstories[1], title: Appstring.prophetsTitles[1]),
    Video(Appvideos.prophetsstories[2], title: Appstring.prophetsTitles[2]),
    Video(Appvideos.prophetsstories[3], title: Appstring.prophetsTitles[3]),
    Video(Appvideos.prophetsstories[4], title: Appstring.prophetsTitles[4]),
    Video(Appvideos.prophetsstories[5], title: Appstring.prophetsTitles[5]),
    Video(Appvideos.prophetsstories[6], title: Appstring.prophetsTitles[6]),
    Video(Appvideos.prophetsstories[7], title: Appstring.prophetsTitles[7]),
    Video(Appvideos.prophetsstories[8], title: Appstring.prophetsTitles[8]),

  ];
}

class AkidavideoData {
  static List<Video> akidavideo = [
    Video(Appvideos.akidastories[0], title: Appstring.akidaTitles[0]),
    Video(Appvideos.akidastories[1], title: Appstring.akidaTitles[1]),
    Video(Appvideos.akidastories[2], title: Appstring.akidaTitles[2]),
    Video(Appvideos.akidastories[3], title: Appstring.akidaTitles[3]),
    Video(Appvideos.akidastories[4], title: Appstring.akidaTitles[4]),
    Video(Appvideos.akidastories[5], title: Appstring.akidaTitles[5]),
    Video(Appvideos.akidastories[6], title: Appstring.akidaTitles[6]),
    Video(Appvideos.akidastories[7], title: Appstring.akidaTitles[7]),
    Video(Appvideos.akidastories[8], title: Appstring.akidaTitles[8]),
    Video(Appvideos.akidastories[9], title: Appstring.akidaTitles[9]),
    Video(Appvideos.akidastories[10], title: Appstring.akidaTitles[10]),
    Video(Appvideos.akidastories[11], title: Appstring.akidaTitles[11]),
    Video(Appvideos.akidastories[12], title: Appstring.akidaTitles[12]),
    Video(Appvideos.akidastories[13], title: Appstring.akidaTitles[13]),
    Video(Appvideos.akidastories[14], title: Appstring.akidaTitles[14]),
    Video(Appvideos.akidastories[15], title: Appstring.akidaTitles[15]),
    Video(Appvideos.akidastories[16], title: Appstring.akidaTitles[16]),
    Video(Appvideos.akidastories[17], title: Appstring.akidaTitles[17]),
    Video(Appvideos.akidastories[18], title: Appstring.akidaTitles[18]),
    Video(Appvideos.akidastories[19], title: Appstring.akidaTitles[19]),
    Video(Appvideos.akidastories[20], title: Appstring.akidaTitles[20]),
    Video(Appvideos.akidastories[21], title: Appstring.akidaTitles[21]),
  ];
}

class QurankreemvideoData {
  static List<Video> qurankreemvideo = [
    Video(Appvideos.qurankreem[1], title: Appstring.quranTitles[1]),
    Video(Appvideos.qurankreem[2], title: Appstring.quranTitles[2]),
    Video(Appvideos.qurankreem[3], title: Appstring.quranTitles[3]),
    Video(Appvideos.qurankreem[4], title: Appstring.quranTitles[4]),
    Video(Appvideos.qurankreem[5], title: Appstring.quranTitles[5]),
    Video(Appvideos.qurankreem[6], title: Appstring.quranTitles[6]),
    Video(Appvideos.qurankreem[7], title: Appstring.quranTitles[7]),
    Video(Appvideos.qurankreem[8], title: Appstring.quranTitles[8]),
    Video(Appvideos.qurankreem[9], title: Appstring.quranTitles[9]),
    Video(Appvideos.qurankreem[10], title: Appstring.quranTitles[10]),
    Video(Appvideos.qurankreem[11], title: Appstring.quranTitles[11]),
    Video(Appvideos.qurankreem[12], title: Appstring.quranTitles[12]),
    Video(Appvideos.qurankreem[13], title: Appstring.quranTitles[13]),
    Video(Appvideos.qurankreem[14], title: Appstring.quranTitles[14]),
    Video(Appvideos.qurankreem[15], title: Appstring.quranTitles[15]),
    Video(Appvideos.qurankreem[16], title: Appstring.quranTitles[16]),
    Video(Appvideos.qurankreem[17], title: Appstring.quranTitles[17]),
    Video(Appvideos.qurankreem[18], title: Appstring.quranTitles[18]),
    Video(Appvideos.qurankreem[19], title: Appstring.quranTitles[19]),
    Video(Appvideos.qurankreem[20], title: Appstring.quranTitles[20]),
    Video(Appvideos.qurankreem[21], title: Appstring.quranTitles[21]),
    Video(Appvideos.qurankreem[22], title: Appstring.quranTitles[22]),
    Video(Appvideos.qurankreem[23], title: Appstring.quranTitles[23]),
    Video(Appvideos.qurankreem[24], title: Appstring.quranTitles[24]),
    Video(Appvideos.qurankreem[25], title: Appstring.quranTitles[25]),
    Video(Appvideos.qurankreem[26], title: Appstring.quranTitles[26]),
    Video(Appvideos.qurankreem[27], title: Appstring.quranTitles[27]),
    Video(Appvideos.qurankreem[28], title: Appstring.quranTitles[28]),
    Video(Appvideos.qurankreem[29], title: Appstring.quranTitles[29]),
    Video(Appvideos.qurankreem[30], title: Appstring.quranTitles[30]),
    Video(Appvideos.qurankreem[31], title: Appstring.quranTitles[31]),
    Video(Appvideos.qurankreem[32], title: Appstring.quranTitles[32]),
    Video(Appvideos.qurankreem[33], title: Appstring.quranTitles[33]),
    Video(Appvideos.qurankreem[34], title: Appstring.quranTitles[34]),
    Video(Appvideos.qurankreem[35], title: Appstring.quranTitles[35]),
    Video(Appvideos.qurankreem[0], title: Appstring.quranTitles[0]),
  ];
}

class HumanvideoData {
  static List<Video> humanvideo = [
    Video(Appvideos.humanstories[0], title: Appstring.humanTitles[0]),
    Video(Appvideos.humanstories[1], title: Appstring.humanTitles[1]),
    Video(Appvideos.humanstories[2], title: Appstring.humanTitles[2]),
    Video(Appvideos.humanstories[3], title: Appstring.humanTitles[3]),
    Video(Appvideos.humanstories[4], title: Appstring.humanTitles[4]),
    Video(Appvideos.humanstories[5], title: Appstring.humanTitles[5]),
    Video(Appvideos.humanstories[6], title: Appstring.humanTitles[6]),
    Video(Appvideos.humanstories[7], title: Appstring.humanTitles[7]),
    Video(Appvideos.humanstories[8], title: Appstring.humanTitles[8]),
    Video(Appvideos.humanstories[9], title: Appstring.humanTitles[9]),
    Video(Appvideos.humanstories[10], title: Appstring.humanTitles[10]),
    Video(Appvideos.humanstories[11], title: Appstring.humanTitles[11]),
    Video(Appvideos.humanstories[12], title: Appstring.humanTitles[12]),
    Video(Appvideos.humanstories[13], title: Appstring.humanTitles[13]),
    Video(Appvideos.humanstories[14], title: Appstring.humanTitles[14]),
    Video(Appvideos.humanstories[15], title: Appstring.humanTitles[15]),
    Video(Appvideos.humanstories[16], title: Appstring.humanTitles[16]),
    Video(Appvideos.humanstories[17], title: Appstring.humanTitles[17]),
    Video(Appvideos.humanstories[18], title: Appstring.humanTitles[18]),
    Video(Appvideos.humanstories[19], title: Appstring.humanTitles[19]),
    Video(Appvideos.humanstories[20], title: Appstring.humanTitles[20]),
    Video(Appvideos.humanstories[21], title: Appstring.humanTitles[21]),
    Video(Appvideos.humanstories[22], title: Appstring.humanTitles[22]),
    Video(Appvideos.humanstories[23], title: Appstring.humanTitles[23]),
    Video(Appvideos.humanstories[24], title: Appstring.humanTitles[24]),
    Video(Appvideos.humanstories[25], title: Appstring.humanTitles[25]),
    Video(Appvideos.humanstories[26], title: Appstring.humanTitles[26]),
  ];
}

class AyatvideoData {
  static List<Video> ayatvideo = [
    Video(Appvideos.ayatstories[0], title: Appstring.ayatstoriesTitles[0]),
    Video(Appvideos.ayatstories[1], title: Appstring.ayatstoriesTitles[1]),
    Video(Appvideos.ayatstories[2], title: Appstring.ayatstoriesTitles[2]),
    Video(Appvideos.ayatstories[3], title: Appstring.ayatstoriesTitles[3]),
    Video(Appvideos.ayatstories[4], title: Appstring.ayatstoriesTitles[4]),
    Video(Appvideos.ayatstories[5], title: Appstring.ayatstoriesTitles[5]),
    Video(Appvideos.ayatstories[6], title: Appstring.ayatstoriesTitles[6]),
    Video(Appvideos.ayatstories[7], title: Appstring.ayatstoriesTitles[7]),
    Video(Appvideos.ayatstories[8], title: Appstring.ayatstoriesTitles[8]),
    Video(Appvideos.ayatstories[9], title: Appstring.ayatstoriesTitles[9]),
    Video(Appvideos.ayatstories[10], title: Appstring.ayatstoriesTitles[10]),
    Video(Appvideos.ayatstories[11], title: Appstring.ayatstoriesTitles[11]),
    Video(Appvideos.ayatstories[12], title: Appstring.ayatstoriesTitles[12]),
    Video(Appvideos.ayatstories[13], title: Appstring.ayatstoriesTitles[13]),
    Video(Appvideos.ayatstories[14], title: Appstring.ayatstoriesTitles[14]),
    Video(Appvideos.ayatstories[15], title: Appstring.ayatstoriesTitles[15]),
    Video(Appvideos.ayatstories[16], title: Appstring.ayatstoriesTitles[16]),
    Video(Appvideos.ayatstories[17], title: Appstring.ayatstoriesTitles[17]),
    Video(Appvideos.ayatstories[18], title: Appstring.ayatstoriesTitles[18]),
    Video(Appvideos.ayatstories[19], title: Appstring.ayatstoriesTitles[19]),
    Video(Appvideos.ayatstories[20], title: Appstring.ayatstoriesTitles[20]),
    Video(Appvideos.ayatstories[21], title: Appstring.ayatstoriesTitles[21]),
    Video(Appvideos.ayatstories[22], title: Appstring.ayatstoriesTitles[22]),
    Video(Appvideos.ayatstories[23], title: Appstring.ayatstoriesTitles[23]),
    Video(Appvideos.ayatstories[24], title: Appstring.ayatstoriesTitles[24]),
    Video(Appvideos.ayatstories[25], title: Appstring.ayatstoriesTitles[25]),
    Video(Appvideos.ayatstories[26], title: Appstring.ayatstoriesTitles[26]),
    Video(Appvideos.ayatstories[27], title: Appstring.ayatstoriesTitles[27]),
    Video(Appvideos.ayatstories[28], title: Appstring.ayatstoriesTitles[28]),
  ];
}

class AnimalQuranvideoData {
  static List<Video> animalQuranvideo = [
    Video(Appvideos.animalQuranstories[0],
        title: Appstring.animalQuranTitles[0]),
    Video(Appvideos.animalQuranstories[1],
        title: Appstring.animalQuranTitles[1]),
    Video(Appvideos.animalQuranstories[2],
        title: Appstring.animalQuranTitles[2]),
    Video(Appvideos.animalQuranstories[3],
        title: Appstring.animalQuranTitles[3]),
    Video(Appvideos.animalQuranstories[4],
        title: Appstring.animalQuranTitles[4]),
    Video(Appvideos.animalQuranstories[5],
        title: Appstring.animalQuranTitles[5]),
    Video(Appvideos.animalQuranstories[6],
        title: Appstring.animalQuranTitles[6]),
    Video(Appvideos.animalQuranstories[7],
        title: Appstring.animalQuranTitles[7]),
    Video(Appvideos.animalQuranstories[8],
        title: Appstring.animalQuranTitles[8]),
    Video(Appvideos.animalQuranstories[9],
        title: Appstring.animalQuranTitles[9]),
    Video(Appvideos.animalQuranstories[10],
        title: Appstring.animalQuranTitles[10]),
    Video(Appvideos.animalQuranstories[11],
        title: Appstring.animalQuranTitles[11]),
    Video(Appvideos.animalQuranstories[12],
        title: Appstring.animalQuranTitles[12]),
    Video(Appvideos.animalQuranstories[13],
        title: Appstring.animalQuranTitles[13]),
    Video(Appvideos.animalQuranstories[14],
        title: Appstring.animalQuranTitles[14]),
    Video(Appvideos.animalQuranstories[15],
        title: Appstring.animalQuranTitles[15]),
    Video(Appvideos.animalQuranstories[16],
        title: Appstring.animalQuranTitles[16]),
    Video(Appvideos.animalQuranstories[17],
        title: Appstring.animalQuranTitles[17]),
    Video(Appvideos.animalQuranstories[18],
        title: Appstring.animalQuranTitles[18]),
    Video(Appvideos.animalQuranstories[19],
        title: Appstring.animalQuranTitles[19]),
    Video(Appvideos.animalQuranstories[20],
        title: Appstring.animalQuranTitles[20]),
    Video(Appvideos.animalQuranstories[21],
        title: Appstring.animalQuranTitles[21]),
    Video(Appvideos.animalQuranstories[22],
        title: Appstring.animalQuranTitles[22]),
    Video(Appvideos.animalQuranstories[23],
        title: Appstring.animalQuranTitles[23]),
    Video(Appvideos.animalQuranstories[24],
        title: Appstring.animalQuranTitles[24]),
    Video(Appvideos.animalQuranstories[25],
        title: Appstring.animalQuranTitles[25]),
    Video(Appvideos.animalQuranstories[26],
        title: Appstring.animalQuranTitles[26]),
    Video(Appvideos.animalQuranstories[27],
        title: Appstring.animalQuranTitles[27]),
    Video(Appvideos.animalQuranstories[28],
        title: Appstring.animalQuranTitles[28]),
    Video(Appvideos.animalQuranstories[29],
        title: Appstring.animalQuranTitles[29]),
  ];
}

class WomenvideoData {
  static List<Video> womenvideo = [
    Video(Appvideos.womenStories[0], title: Appstring.womenStoriesTitles[0]),
    Video(Appvideos.womenStories[1], title: Appstring.womenStoriesTitles[1]),
    Video(Appvideos.womenStories[2], title: Appstring.womenStoriesTitles[2]),
    Video(Appvideos.womenStories[3], title: Appstring.womenStoriesTitles[3]),
    Video(Appvideos.womenStories[4], title: Appstring.womenStoriesTitles[4]),
    Video(Appvideos.womenStories[5], title: Appstring.womenStoriesTitles[5]),
    Video(Appvideos.womenStories[6], title: Appstring.womenStoriesTitles[6]),
    Video(Appvideos.womenStories[7], title: Appstring.womenStoriesTitles[7]),
    Video(Appvideos.womenStories[8], title: Appstring.womenStoriesTitles[8]),
    Video(Appvideos.womenStories[9], title: Appstring.womenStoriesTitles[9]),
    Video(Appvideos.womenStories[10], title: Appstring.womenStoriesTitles[10]),
    Video(Appvideos.womenStories[11], title: Appstring.womenStoriesTitles[11]),
    Video(Appvideos.womenStories[12], title: Appstring.womenStoriesTitles[12]),
    Video(Appvideos.womenStories[13], title: Appstring.womenStoriesTitles[13]),
    Video(Appvideos.womenStories[14], title: Appstring.womenStoriesTitles[14]),
    Video(Appvideos.womenStories[15], title: Appstring.womenStoriesTitles[15]),
    Video(Appvideos.womenStories[16], title: Appstring.womenStoriesTitles[16]),
    Video(Appvideos.womenStories[17], title: Appstring.womenStoriesTitles[17]),
    Video(Appvideos.womenStories[18], title: Appstring.womenStoriesTitles[18]),
    Video(Appvideos.womenStories[19], title: Appstring.womenStoriesTitles[19]),
    Video(Appvideos.womenStories[20], title: Appstring.womenStoriesTitles[20]),
    Video(Appvideos.womenStories[21], title: Appstring.womenStoriesTitles[21]),
    Video(Appvideos.womenStories[22], title: Appstring.womenStoriesTitles[22]),
    Video(Appvideos.womenStories[23], title: Appstring.womenStoriesTitles[23]),
    Video(Appvideos.womenStories[24], title: Appstring.womenStoriesTitles[24]),
    Video(Appvideos.womenStories[25], title: Appstring.womenStoriesTitles[25]),
    Video(Appvideos.womenStories[26], title: Appstring.womenStoriesTitles[26]),
    Video(Appvideos.womenStories[27], title: Appstring.womenStoriesTitles[27]),
    Video(Appvideos.womenStories[28], title: Appstring.womenStoriesTitles[28]),
    Video(Appvideos.womenStories[29], title: Appstring.womenStoriesTitles[29]),
  ];
}
